headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/openclaw/projects/berkah-website/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[[build.environment]]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/id/1ai"
to = "/id/one-ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en/1ai"
to = "/en/one-ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/id/omniroute"
to = "/id/one-ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en/omniroute"
to = "/en/one-ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/omniroute"
to = "/id/one-ai"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]